routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//Backend
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\OrderController;

//Frontend
use App\Http\Controllers\Frontend\IndexController as FrontendIndex;
use App\Http\Controllers\Frontend\LoginController as FrontendLogin;
use App\Http\Controllers\Frontend\CartController as FrontendCart;
use App\Http\Controllers\Frontend\CheckoutController as FrontendCheckout;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/starter', function () {
//    return view('backend.starter');
//});
//
//Route::get('/dashboard', function () {
//    return view('backend.dashboard');
//});
//
//Route::get('/products', function () {
//    return view('backend.products.dashboard');
//});
//Route::get('/products/create', function () {
//    return view('backend.products.create');
//});
//Route::get('/login', function () {
//    return view('backend.auth.login');
//});

Route::get('/', [FrontendIndex::class, 'index'])->name('home');
Route::get('/login', [FrontendLogin::class, 'login'])->name('login');
Route::post('/login', [FrontendLogin::class, 'authenticate']);
Route::get('/logout', [FrontendLogin::class, 'logout'])->name('logout');

Route::get('/cart', function () {
    return view('frontend.cart.cart');
})->name('cart.show');

Route::get('/checkout', function () {
    return view('frontend.payment.checkout');
})->name('checkout.show');
Route::get('/checkout/result', function () {
    return view('frontend.payment.result');
})->name('checkout.result');

Route::middleware('auth')->group(function () {
    Route::post('cart/add', [FrontendCart::class, 'add'])->name('cart.add');
    Route::get('cart/remove/{cart}', [FrontendCart::class, 'remove'])->name('cart.remove');
    Route::post('cart/update/{cart}', [FrontendCart::class, 'update'])->name('cart.update');
    Route::post('checkout', [FrontendCheckout::class, 'store'])->name('checkout.store');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('login', [LoginController::class, 'login'])->name('login');
    Route::post('login', [LoginController::class, 'authenticate']);

    Route::middleware('check.role')->group(function () {
        Route::get('/', [DashboardController::class, 'index']);
        Route::get('logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
        //Products
        Route::resource('products', ProductController::class);
        Route::resource('orders', OrderController::class);
        Route::post('orders/updateStatus', [OrderController::class,'updateStatus'])->name('orders.updateStatus');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    public function index()
    {
        if (!Auth::check()) {
            return redirect()->route('admin.login');
        }

        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{

    public function login()
    {
        return view('backend.auth.login');
    }

    public function authenticate(Request $request)
    {
        $credentials = $request->validate([
            'email' => 'required|email',
            'password' => 'required'
        ]);

        if (Auth::attempt($credentials)) {
            return redirect()->intended(route('admin.dashboard'));
        }

        return back()->with('error', 'Hatalı email yada şifre');
    }

    public function logout()
    {
        Auth::logout();
        return redirect(route('admin.login'))->with('success', 'Güvenli Çıkış Yaptınız.');
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::with('user')->get();
        return view('backend.orders.index',compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::with('orderItems.product','user','address')->findOrFail($id);
        return view('backend.orders.show',compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function updateStatus(Request $request)
    {
        $order = Order::find($request->id);
        $order->status = $request->status;
        $order = $order->save();
        if ($order) return true;
        return false;
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('backend.products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'price'=>'required|numeric',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
        ]);
        $product = new Product;
        $path = '';
        if($request->hasFile('image')){
            $path = '/storage/'.$request->image->store('uploads/products','public');
        }
        $product->title = $request->title;
        $product->slug = Str::slug($request->title);
        $product->body = $request->body;
        $product->price = $request->price;
        $product->image = $path;
        $is_save = $product->save();
        if($is_save){
            return redirect(route('admin.products.index'))->with('success','İşlem Başarılı');
        }
        return back()->with('error','İşlem Başarısız');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('backend.products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=>'required',
            'price'=>'required|numeric',
            'image' => 'sometimes|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
        ]);
        $product = Product::find($id);

        $oldFile = '';
        if($request->hasFile('image')){
            $oldFile = $product->image;
            $path = '/storage/'.$request->image->store('uploads/products','public');
            $product->image = $path;
        }
        $product->title = $request->title;
        $product->slug = Str::slug($request->title);
        $product->body = $request->body;
        $product->price = $request->price;
        $is_save = $product->save();
        if($is_save){
            if (Storage::disk('public')->exists($oldFile)) {
                Storage::disk('public')->delete($oldFile);
            }
            return redirect(route('admin.products.index'))->with('success','İşlem Başarılı');
        }
        return back()->with('error','İşlem Başarısız');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find(intval($id));
        $file = $product->file;
        if ($product->delete()){
            if (Storage::disk('public')->exists($file)) {
                Storage::disk('public')->delete($file);
            }
            return true;
        }
        return false;
    }
}

resources/views/backend/products/create.blade.php
@extends('backend.layouts.master')
@section('page-nav')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>
                        Ürün
                        <small>Ekle</small>
                    </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}" class="text-orange nav__link">Anasayfa</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.products.index')}}" class="text-orange nav__link">Liste</a></li>
                        <li class="breadcrumb-item active">Ekle</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- ./row -->
            <div class="row">
                <div class="col-12">
                    <div class="card card-olive card-outline card-tabs">
                        <!-- /.general -->
                        <div class="card-body">
                            <form action="{{route('admin.products.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label>Adı</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input type="text" class="form-control" name="title" value="{{old('title')}}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Fiyat</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input type="number" min="0" step="any" class="form-control" name="price" value="{{old('price')}}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Açıklama</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <textarea id="body" name="body" class="form-control editors">{!! old('body') !!}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Görsel<span class="text-danger small">(Türü: jpeg, png, jpg, gif, svg olmalı ve Max: 1MB olmalıdır.)</span></label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input id="image" type="file" name="image" class="form-control"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="user-image mb-3 text-center">
                                    <div class="imgPreview"> </div>
                                </div>
                                <hr>

                                <div class="text-center">
                                    <button type="submit" class="btn bg-olive">Kaydet</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection
@section('styles')
    <style>
        .imgPreview img{max-height: 150px; border:1px solid #ddd; margin:5px;}
    </style>
@endsection
@section('scripts')
    <script>
        $(function() {
            // Multiple images preview with JavaScript
            var multiImgPreview = function(input, imgPreviewPlaceholder) {

                if (input.files) {
                    var filesAmount = input.files.length;

                    for (i = 0; i < filesAmount; i++) {
                        var reader = new FileReader();

                        reader.onload = function(event) {
                            $($.parseHTML('<img>')).attr('src', event.target.result).appendTo(imgPreviewPlaceholder);
                        }

                        reader.readAsDataURL(input.files[i]);
                    }
                }

            };

            $('#image').on('change', function() {
                $('.imgPreview').empty();
                multiImgPreview(this, 'div.imgPreview');
            });
        });
    </script>
@endsection

resources/views/backend/products/edit.blade.php
@extends('backend.layouts.master')
@section('page-nav')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>
                        Ürün
                        <small>Düzenle</small>
                    </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}" class="text-orange nav__link">Anasayfa</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.products.index')}}" class="text-orange nav__link">Liste</a></li>
                        <li class="breadcrumb-item active">Düzenle</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- ./row -->
            <div class="row">
                <div class="col-12">
                    <div class="card card-olive card-outline card-tabs">
                        <!-- /.general -->
                        <div class="card-body">
                            <form action="{{route('admin.products.update',$product->id)}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label>Adı</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input type="text" class="form-control" name="title" value="{{$product->title}}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Fiyat</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input type="number" min="0" step="any" class="form-control" name="price" value="{{$product->price}}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Açıklama</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <textarea id="body" name="body" class="form-control editors">{!! $product->body !!}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Mevcut Görsel</label>
                                    <div class="row">
                                        <div class="col-12">
                                            <img width="150" src="{{$product->image}}" alt="img">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Görsel<span class="text-danger small">(Türü: jpeg, png, jpg, gif, svg olmalı ve Max: 1MB olmalıdır.)</span></label>
                                    <div class="row">
                                        <div class="col-12">
                                            <input id="image" type="file" name="image" class="form-control"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="user-image mb-3 text-center">
                                    <div class="imgPreview"> </div>
                                </div>
                                <hr>

                                <div class="text-center">
                                    <button type="submit" class="btn bg-olive">Kaydet</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection
@section('styles')
    <style>
        .imgPreview img{max-height: 150px; border:1px solid #ddd; margin:5px;}
    </style>
@endsection
@section('scripts')
    <script>
        $(function() {
            // Multiple images preview with JavaScript
            var multiImgPreview = function(input, imgPreviewPlaceholder) {

                if (input.files) {
                    var filesAmount = input.files.length;

                    for (i = 0; i < filesAmount; i++) {
                        var reader = new FileReader();

                        reader.onload = function(event) {
                            $($.parseHTML('<img>')).attr('src', event.target.result).appendTo(imgPreviewPlaceholder);
                        }

                        reader.readAsDataURL(input.files[i]);
                    }
                }

            };

            $('#image').on('change', function() {
                $('.imgPreview').empty();
                multiImgPreview(this, 'div.imgPreview');
            });
        });
    </script>
@endsection

resources/views/backend/products/index.blade.php
@extends('backend.layouts.master')
@section('page-nav')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>
                        Ürün
                        <small>Liste</small>
                    </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}" class="text-orange nav__link">Anasayfa</a></li>
                        <li class="breadcrumb-item active">Liste</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header text-center">
                        <h3 class="card-title float-none">
                            <a href="{{route('admin.products.create')}}" class="btn btn-dark">Ürün Ekle</a>
                            <div class="card-tools float-right">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th width="10">#</th>
                                <th>Görsel</th>
                                <th>Adı</th>
                                <th>Adı</th>
                                <th width="10">İşlem</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($products as $product)
                                <tr id="item-{{$product->id}}">
                                    <td>{{$loop->iteration}}</td>
                                    <td><img height="50" src="{{$product->image}}" alt="image"></td>
                                    <td>{{$product->title}}</td>
                                    <td>{{$product->price}}</td>
                                    <td class="text-center">
                                        <div class="btn-group btn-group-sm">
                                            <a href="{{route('admin.products.edit',$product->id)}}" title="Düzenle" class="btn btn-warning">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a id="{{$product->id}}" href="javascript:void(0);" title="Sil" class="btn btn-danger delete-btn">
                                                <i class="fas fa-trash-alt"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection
@section('styles')

@endsection
@section('scripts')
<script>
    $(()=>{
        $('.delete-btn').on('click',function(){
            let id = $(this).attr('id');
            deleteItem('products',id,);
        });
    })
</script>
@endsection