routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//Backend
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\OrderController;

//Frontend
use App\Http\Controllers\Frontend\IndexController as FrontendIndex;
use App\Http\Controllers\Frontend\LoginController as FrontendLogin;
use App\Http\Controllers\Frontend\CartController as FrontendCart;
use App\Http\Controllers\Frontend\CheckoutController as FrontendCheckout;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/starter', function () {
//    return view('backend.starter');
//});
//
//Route::get('/dashboard', function () {
//    return view('backend.dashboard');
//});
//
//Route::get('/products', function () {
//    return view('backend.products.dashboard');
//});
//Route::get('/products/create', function () {
//    return view('backend.products.create');
//});
//Route::get('/login', function () {
//    return view('backend.auth.login');
//});

Route::get('/', [FrontendIndex::class, 'index'])->name('home');
Route::get('/login', [FrontendLogin::class, 'login'])->name('login');
Route::post('/login', [FrontendLogin::class, 'authenticate']);
Route::get('/logout', [FrontendLogin::class, 'logout'])->name('logout');

Route::get('/cart', function () {
    return view('frontend.cart.cart');
})->name('cart.show');

Route::get('/checkout', function () {
    return view('frontend.payment.checkout');
})->name('checkout.show');
Route::get('/checkout/result', function () {
    return view('frontend.payment.result');
})->name('checkout.result');

Route::middleware('auth')->group(function () {
    Route::post('cart/add', [FrontendCart::class, 'add'])->name('cart.add');
    Route::get('cart/remove/{cart}', [FrontendCart::class, 'remove'])->name('cart.remove');
    Route::post('cart/update/{cart}', [FrontendCart::class, 'update'])->name('cart.update');
    Route::post('checkout', [FrontendCheckout::class, 'store'])->name('checkout.store');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('login', [LoginController::class, 'login'])->name('login');
    Route::post('login', [LoginController::class, 'authenticate']);

    Route::middleware('check.role')->group(function () {
        Route::get('/', [DashboardController::class, 'index']);
        Route::get('logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
        //Products
        Route::resource('products', ProductController::class);
        Route::resource('orders', OrderController::class);
        Route::post('orders/updateStatus', [OrderController::class,'updateStatus'])->name('orders.updateStatus');
    });
});

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    public function index()
    {
        if (!Auth::check()) {
            return redirect()->route('admin.login');
        }

        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{

    public function login()
    {
        return view('backend.auth.login');
    }

    public function authenticate(Request $request)
    {
        $credentials = $request->validate([
            'email' => 'required|email',
            'password' => 'required'
        ]);

        if (Auth::attempt($credentials)) {
            return redirect()->intended(route('admin.dashboard'));
        }

        return back()->with('error', 'Hatalı email yada şifre');
    }

    public function logout()
    {
        Auth::logout();
        return redirect(route('admin.login'))->with('success', 'Güvenli Çıkış Yaptınız.');
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::with('user')->get();
        return view('backend.orders.index',compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::with('orderItems.product','user','address')->findOrFail($id);
        return view('backend.orders.show',compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function updateStatus(Request $request)
    {
        $order = Order::find($request->id);
        $order->status = $request->status;
        $order = $order->save();
        if ($order) return true;
        return false;
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('backend.products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'price'=>'required|numeric',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
        ]);
        $product = new Product;
        $path = '';
        if($request->hasFile('image')){
            $path = '/storage/'.$request->image->store('uploads/products','public');
        }
        $product->title = $request->title;
        $product->slug = Str::slug($request->title);
        $product->body = $request->body;
        $product->price = $request->price;
        $product->image = $path;
        $is_save = $product->save();
        if($is_save){
            return redirect(route('admin.products.index'))->with('success','İşlem Başarılı');
        }
        return back()->with('error','İşlem Başarısız');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('backend.products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=>'required',
            'price'=>'required|numeric',
            'image' => 'sometimes|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
        ]);
        $product = Product::find($id);

        $oldFile = '';
        if($request->hasFile('image')){
            $oldFile = $product->image;
            $path = '/storage/'.$request->image->store('uploads/products','public');
            $product->image = $path;
        }
        $product->title = $request->title;
        $product->slug = Str::slug($request->title);
        $product->body = $request->body;
        $product->price = $request->price;
        $is_save = $product->save();
        if($is_save){
            if (Storage::disk('public')->exists($oldFile)) {
                Storage::disk('public')->delete($oldFile);
            }
            return redirect(route('admin.products.index'))->with('success','İşlem Başarılı');
        }
        return back()->with('error','İşlem Başarısız');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find(intval($id));
        $file = $product->file;
        if ($product->delete()){
            if (Storage::disk('public')->exists($file)) {
                Storage::disk('public')->delete($file);
            }
            return true;
        }
        return false;
    }
}

resources/views/backend/layouts/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
{{--    <div class="float-right d-none d-sm-inline">--}}
{{--        Anything you want--}}
{{--    </div>--}}
    <!-- Default to the left -->
    <strong>Copyright &copy; 2021 <a href="https://bircom.com" target="_blank">Bircom</a>.</strong> All rights reserved.
</footer>

resources/views/backend/layouts/master.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Admin</title>


    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/fontawesome-free/css/all.min.css')}}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <!-- alertify -->
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/alertify/alertify.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/alertify/default.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/alertify/semantic.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/alertify/bootstrap.min.css')}}">
    <!-- jquery-ui -->
    <link rel="stylesheet" href="{{asset('assets/backend/plugins/jquery-ui/jquery-ui.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('assets/backend/dist/css/adminlte.css')}}">

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    @yield('styles')
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
    @include('backend.layouts.navbar')
    @include('backend.layouts.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @yield('page-nav')
        @yield('content')
    </div>
    <!-- /.content-wrapper -->

    @include('backend.layouts.footer')
    @include('backend.partials.alertify')
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{asset('assets/backend/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('assets/backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- Bootstrap Switch -->
<script src="{{asset('assets/backend/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>
<!-- Select2 -->
<script src="{{asset('assets/backend/plugins/select2/js/select2.full.min.js')}}"></script>
<!-- DataTables -->
<script src="{{asset('assets/backend/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/backend/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<!-- alertify -->
<script src="{{asset('assets/backend/plugins/alertify/alertify.min.js')}}"></script>
<!-- jquery-ui -->
<script src="{{asset('assets/backend/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- ckeditor -->
<script src="{{asset('assets/backend/plugins/ckeditor/ckeditor.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('assets/backend/dist/js/adminlte.min.js')}}"></script>
<script>
    $(()=>{
        // ajaxSetup
        $(function(){
            $.ajaxSetup({
                headers:{
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        });
        $('#example1_paginate').on('click',function(){
            $("input[data-bootstrap-switch]").each(function(){
                $(this).bootstrapSwitch('state', $(this).prop('checked'));
            });
        });
        // on - off
        $(function () {
            $("input[data-bootstrap-switch]").each(function(){
                $(this).bootstrapSwitch('state', $(this).prop('checked'));
            });
        });
        //datatable set lang
        $(function () {
            $("#example1").DataTable();
        });
        //Initialize Select2 Elements
        $('.select2').select2();



    });
    //CKEditor
    const allEditors = document.querySelectorAll('.editors');
    for (let i = 0; i < allEditors.length; ++i) {
        CKEDITOR.replace( allEditors[i]);
    }
    //CKEDITOR.config.autoParagraph = false;

    function deleteItem(route,id,item='#item-') {
        alertify.confirm("Kalıcı olarak silmek istediğinize emin misiniz?","Bu işlem geri alınamaz",()=>{
            $.ajax({
                type:'delete',
                url:route+'/'+id,
                success:function(res){
                    if(res){
                        $(item + id).remove();
                        alertify.success('Kayıt Silindi.');
                    }else{
                        alertify.error('Kayıt Silinemedi.');
                    }
                }
            });
        },()=>{
            alertify.error("Silme işlemi iptal edildi.");
        });
    }
</script>
@yield('scripts')
</body>
</html>

resources/views/backend/layouts/navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="javascript:void(0);">
                <img src="{{asset('assets/backend/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2 h-100" alt="User Image">
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">Profil</a>
                <a href="{{route('admin.logout')}}" class="dropdown-item">Çıkış Yap</a>
            </div>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/backend/layouts/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-olive elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="{{asset('assets/backend/dist/img/AdminLTELogo.png')}}" alt="logo" class="brand-image elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Bircom</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset('assets/backend/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Admin</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!--Dashboard-->
                <li class="nav-item">
                    <a href="{{route('admin.dashboard')}}" class="nav-link {{ (request()->is('admin/dashboard')) ? 'active' : '' }}"><i class="nav-icon fas fa-th-large"></i><p>Anasayfa</p></a>
                </li>
                <!--Orders-->
                <li class="nav-item">
                    <a href="{{route('admin.orders.index')}}" class="nav-link {{ (request()->is('admin/orders*')) ? 'active' : '' }}"><i class="nav-icon fas fa-cart-plus"></i><p>Siparişler</p></a>
                </li>
                <!--Products-->
                <li class="nav-item has-treeview {{ (request()->is('admin/products*')) ? 'menu-open' : '' }}">
                    <a href="#" class="nav-link {{ (request()->is('admin/products*')) ? 'active' : '' }}">
                        <i class="nav-icon fas fa-tags"></i>
                        <p>Ürünler <i class="right fas fa-angle-left"></i></p>
                    </a>
                    <ul class="nav nav-treeview pl-3">
                        <li class="nav-item">
                            <a href="{{route('admin.products.index')}}" class="nav-link"><i class="fas fa-list-ol nav-icon"></i><p>Liste</p></a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.products.create')}}" class="nav-link"><i class="fas fa-plus-square nav-icon"></i><p>Ekle</p></a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>