routes/web.php
<?php

use Illuminate\Support\Facades\Route;
//Backend
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\OrderController;

//Frontend
use App\Http\Controllers\Frontend\IndexController as FrontendIndex;
use App\Http\Controllers\Frontend\LoginController as FrontendLogin;
use App\Http\Controllers\Frontend\CartController as FrontendCart;
use App\Http\Controllers\Frontend\CheckoutController as FrontendCheckout;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::get('/starter', function () {
//    return view('backend.starter');
//});
//
//Route::get('/dashboard', function () {
//    return view('backend.dashboard');
//});
//
//Route::get('/products', function () {
//    return view('backend.products.dashboard');
//});
//Route::get('/products/create', function () {
//    return view('backend.products.create');
//});
//Route::get('/login', function () {
//    return view('backend.auth.login');
//});

Route::get('/', [FrontendIndex::class, 'index'])->name('home');
Route::get('/login', [FrontendLogin::class, 'login'])->name('login');
Route::post('/login', [FrontendLogin::class, 'authenticate']);
Route::get('/logout', [FrontendLogin::class, 'logout'])->name('logout');

Route::get('/cart', function () {
    return view('frontend.cart.cart');
})->name('cart.show');

Route::get('/checkout', function () {
    return view('frontend.payment.checkout');
})->name('checkout.show');
Route::get('/checkout/result', function () {
    return view('frontend.payment.result');
})->name('checkout.result');

Route::middleware('auth')->group(function () {
    Route::post('cart/add', [FrontendCart::class, 'add'])->name('cart.add');
    Route::get('cart/remove/{cart}', [FrontendCart::class, 'remove'])->name('cart.remove');
    Route::post('cart/update/{cart}', [FrontendCart::class, 'update'])->name('cart.update');
    Route::post('checkout', [FrontendCheckout::class, 'store'])->name('checkout.store');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('login', [LoginController::class, 'login'])->name('login');
    Route::post('login', [LoginController::class, 'authenticate']);

    Route::middleware('check.role')->group(function () {
        Route::get('/', [DashboardController::class, 'index']);
        Route::get('logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
        //Products
        Route::resource('products', ProductController::class);
        Route::resource('orders', OrderController::class);
        Route::post('orders/updateStatus', [OrderController::class,'updateStatus'])->name('orders.updateStatus');
    });
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function orderItems()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function user()
    {
        return $this->hasOne(User::class,'id','user_id');
    }
    public function address()
    {
        return $this->hasOne(Address::class,'id','address_id');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    public function index()
    {
        if (!Auth::check()) {
            return redirect()->route('admin.login');
        }

        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{

    public function login()
    {
        return view('backend.auth.login');
    }

    public function authenticate(Request $request)
    {
        $credentials = $request->validate([
            'email' => 'required|email',
            'password' => 'required'
        ]);

        if (Auth::attempt($credentials)) {
            return redirect()->intended(route('admin.dashboard'));
        }

        return back()->with('error', 'Hatalı email yada şifre');
    }

    public function logout()
    {
        Auth::logout();
        return redirect(route('admin.login'))->with('success', 'Güvenli Çıkış Yaptınız.');
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::with('user')->get();
        return view('backend.orders.index',compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::with('orderItems.product','user','address')->findOrFail($id);
        return view('backend.orders.show',compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function updateStatus(Request $request)
    {
        $order = Order::find($request->id);
        $order->status = $request->status;
        $order = $order->save();
        if ($order) return true;
        return false;
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('backend.products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'price'=>'required|numeric',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
        ]);
        $product = new Product;
        $path = '';
        if($request->hasFile('image')){
            $path = '/storage/'.$request->image->store('uploads/products','public');
        }
        $product->title = $request->title;
        $product->slug = Str::slug($request->title);
        $product->body = $request->body;
        $product->price = $request->price;
        $product->image = $path;
        $is_save = $product->save();
        if($is_save){
            return redirect(route('admin.products.index'))->with('success','İşlem Başarılı');
        }
        return back()->with('error','İşlem Başarısız');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('backend.products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=>'required',
            'price'=>'required|numeric',
            'image' => 'sometimes|image|mimes:jpeg,png,jpg,gif,svg|max:1024',
        ]);
        $product = Product::find($id);

        $oldFile = '';
        if($request->hasFile('image')){
            $oldFile = $product->image;
            $path = '/storage/'.$request->image->store('uploads/products','public');
            $product->image = $path;
        }
        $product->title = $request->title;
        $product->slug = Str::slug($request->title);
        $product->body = $request->body;
        $product->price = $request->price;
        $is_save = $product->save();
        if($is_save){
            if (Storage::disk('public')->exists($oldFile)) {
                Storage::disk('public')->delete($oldFile);
            }
            return redirect(route('admin.products.index'))->with('success','İşlem Başarılı');
        }
        return back()->with('error','İşlem Başarısız');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find(intval($id));
        $file = $product->file;
        if ($product->delete()){
            if (Storage::disk('public')->exists($file)) {
                Storage::disk('public')->delete($file);
            }
            return true;
        }
        return false;
    }
}

resources/views/backend/orders/index.blade.php
@extends('backend.layouts.master')
@section('page-nav')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>
                        Şipariş
                        <small>Liste</small>
                    </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}" class="text-orange nav__link">Anasayfa</a></li>
                        <li class="breadcrumb-item active">Liste</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">

                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th width="10">#</th>
                                <th>Şipariş No</th>
                                <th>Kullanıcı Adı</th>
                                <th>Ödeme Türü</th>
                                <th>Toplam</th>
                                <th>Durum</th>
                                <th width="10">İşlem</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($orders as $order)
                                <tr id="item-{{$order->id}}">
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$order->order_no}}</td>
                                    <td>{{$order->user->name}}</td>
                                    <td>{{getPaymentType($order->payment_type)}}</td>
                                    <td>{{$order->total}}</td>
                                    <td>
                                        <select name="status" class="form-control status" data-order="{{$order->id}}">
                                            <option value="0" {{$order->status == 0 ? 'selected' : ''}}>Beklemede</option>
                                            <option value="1" {{$order->status == 1 ? 'selected' : ''}}>Onaylandı</option>
                                        </select>
                                    </td>
                                    <td class="text-center">
                                        <div class="btn-group btn-group-sm">
                                            <a href="{{route('admin.orders.show',$order->id)}}" title="Göster" class="btn btn-info">
                                                <i class="fas fa-eye"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection
@section('styles')

@endsection
@section('scripts')
    <script>
        $('.status').on('change',function () {
            $.ajax({
                type:'post',
                url:'{{route("admin.orders.updateStatus")}}',
                data:{
                    status: $(this).val(),
                    id: $(this).data('order')
                },
                success:function(res){
                    if(res){
                        alertify.success('Durum güncellendi');
                    }else{
                        alertify.error('Durum güncellenemedi');
                    }
                }
            });
        })
    </script>
@endsection

resources/views/backend/orders/show.blade.php
@extends('backend.layouts.master')
@section('page-nav')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>
                        Sipariş
                        <small>Detay</small>
                    </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}" class="text-orange nav__link">Anasayfa</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.orders.index')}}" class="text-orange nav__link">Liste</a></li>
                        <li class="breadcrumb-item active">Detay</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- Main content -->
                    <div class="invoice p-3 mb-3">
                        <!-- title row -->
                        <div class="row">
                            <div class="col-12">
                                <h4>
                                    <small class="float-right">Tarih: {{setDateFormat($order->created_at)}}</small>
                                </h4>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- info row -->
                        <div class="row invoice-info">
                            <!-- /.col -->
                            <div class="col-sm-4 invoice-col">
                                <b>Sipariş Bilgisi</b><br>
                                <br>
                                <b>Sipariş No</b> {{$order->order_no}}<br>
                                <b>Ödeme Türü</b> {{getPaymentType($order->payment_type)}}<br>
                                <b>Durum</b> {{getOrderStatus($order->status)}}<br>
                                <b>Toplam Tutar</b> {{$order->total}}<br>
                            </div>
                            <!-- /.col -->
                            <div class="col-sm-4 invoice-col">
                                <b>Adres Bilgisi</b><br>
                                <br>
                                <b>Adres Adı</b> {{$order->address->title}}<br>
                                <b>Adı Soyadı</b> {{$order->address->name}}<br>
                                <b>Email</b> {{$order->address->email}}<br>
                                <b>Telefon</b> {{$order->address->phone}}<br>
                                <b>Adres</b> {{$order->address->address}}<br>
                            </div>
                            <!-- /.col -->
                            <!-- /.col -->
                            <div class="col-sm-4 invoice-col">
                                <b>Kullanıcı Bilgisi</b><br>
                                <br>
                                <b>Adı Soyadı</b> {{$order->user->name}}<br>
                                <b>Email</b> {{$order->user->email}}<br>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->

                        <!-- Table row -->
                        <div class="row">
                            <div class="col-12 table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>Görsel</th>
                                        <th>Adet</th>
                                        <th>Ürün</th>
                                        <th>Fiyat</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($order->orderItems as $item)
                                    <tr>
                                        <td><img height="50" src="{{$item->product->image}}" alt="image"></td>
                                        <td>{{$item->quantity}}</td>
                                        <td>{{$item->product_name}}</td>
                                        <td>{{$item->price}}</td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                        <hr/>
                        <div class="row">
                            <!-- accepted payments column -->
                            <!-- /.col -->
                            <div class="col-12">
                                <div class="float-right">
                                    <strong>Toplam:</strong> <span class="badge badge-success">{{$order->total}}</span>
                                </div>
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->

                    <!-- /.invoice -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection
@section('styles')
@endsection
@section('scripts')
@endsection